### ISSUE TITLE
Withdrawal after assym deposit

### ISSUE THREAD

**Issue by anonfiveone** [SKIPexchange/asgard-exchange#142]
I had entered the BCH.BCH pool assym with THOR.RUNE. I thought it would sell half of the THOR.RUNE to buy BCH.BCH.

When I withdraw and move the slider, it shows that I never withdraw any BCH.BCH (even though I was under impression that I enter the pool 50-50 even in assym).

This is related to issue #135 

![Screen Shot 2021-07-18 at 8 40 49 PM](https://user-images.githubusercontent.com/83097467/126087592-706b0b2c-29f6-4155-a8bb-cc61bfee66ca.png)

**Comment by SKIPexchange** [comment]
Yes, it will (by arbitrages). but because you only bonded your THOR.RUNE address into the BCH pool you can only withdraw fully with THOR.RUNE
See it this way, that it will swap the other half back to RUNE
