### ISSUE TITLE
Approve contract error for swap

### ISSUE THREAD

**Issue by anonfiveone** [SKIPexchange/asgard-exchange#167]
Tried to approve an ETH contract for a ETH.USDT to BNB.BNB swap, got this error:

![Screen Shot 2021-07-19 at 7 43 44 PM](https://user-images.githubusercontent.com/83097467/126241222-158b82e7-77bc-4a80-aa77-d57196f53fe5.png)

**Comment by SKIPexchange** [comment]
Can you specify with which connection this happened? Did you have the chain gas fee? All connections were tested for contract approval :/

**Comment by anonfiveone** [comment]
I don't recall, maybe ETH.USDT? Will try to replicate again.
