### ISSUE TITLE
Swap error with browser extention metamask

### ISSUE THREAD

**Issue by anonfiveone** [SKIPexchange/asgard-exchange#172]
Appeared after confirm was pressed and metamask asked me to approve.

![Screen Shot 2021-07-19 at 8 24 47 PM](https://user-images.githubusercontent.com/83097467/126243980-9a6dde7b-28cd-42f0-bc30-8462b3eb6334.png)

**Comment by SKIPexchange** [comment]
I see. We have to bump the gas fee.
