### ISSUE TITLE
ChaosNet TrustWallet mobile app via WalletConnect

### ISSUE THREAD

**Issue by anonfiveone** [SKIPexchange/asgard-exchange#175]
1) Had a balance of 1.96 THOR.RUNE in my trustwallet using walletconnect, it allowed me to approve a send TX of my entire balance to another address (I thought 3 min rune has to stay in the wallet)?

2) Once I approved the TX on my mobile app, SKIP desktop chaosnet went to "processing" view, but never refreshed to success view. I don't think the TX was ever sent.

**Comment by SKIPexchange** [comment]
With worked for me with even 0.38 amount of rune !!
