### ISSUE TITLE
THOR wallet doesn't show fiat values

### ISSUE THREAD

**Issue by anonfiveone** [SKIPexchange/asgard-exchange#191]
I recently withdrew some THOR.RUNE from pools (but I had a lot of undeposited RUNE left in my wallet).

I went to go see my wallet and the fiat values don't show up for the THOR wallet?

https://user-images.githubusercontent.com/83097467/126679649-0b69c2eb-8f60-4e45-9f69-0a5a49c6b294.mov

**Comment by SKIPexchange** [comment]
It's ok now!
![image](https://user-images.githubusercontent.com/82870243/130662704-12be6bb2-7eda-4594-bde4-6346217ca21a.png)
