### ISSUE TITLE
Discrepancy in wallet fiat values

### ISSUE THREAD

**Issue by anonfiveone** [SKIPexchange/asgard-exchange#192]
None of the wallet fiat values match the asset values.

https://user-images.githubusercontent.com/83097467/126680156-f41c9b9f-1ae9-4735-8d53-87389ea63655.mov

**Comment by SKIPexchange** [comment]
This is because of the price difference between thorchain price oracle and coingecko price api.
This shouldn't be happening on mainnet. but it's normal in testnet because of the unbalanced pools.
