### ISSUE TITLE
Assym / symm withdrawal views

### ISSUE THREAD

**Issue by anonfiveone** [SKIPexchange/asgard-exchange#206]
- [x] Issue 1:

The space above the XXX % of XXX% is not the same as in the fields on the swap views. Should be the same padding.

![IMG_B876E4B2A88C-1](https://user-images.githubusercontent.com/83097467/129646072-99247ae4-facf-4687-a8e0-10f4e9402e0f.jpeg)

-------------------------

- [x] Issue 2:

The styling of the slider in the percentage field is not the same as desktop. You have these 2 weird horizontal lines instead of a nice flat line as designed.

-------------------------

- [x] Issue 3:

The ASSET.ASSET for the withdrawal field should be in the top right (like on symmetrical deposit view).

-------------------------

- [x] Issue 4:

The breadcrumb says "LOADING" and then "PICK PERCENTAGE WITH SLIDER" -- because it starts with LOADING first as a message, the breadcrumb doesn't reposition itself after to see the full "PICK PERCENTAGE WITH SLIDER" after.

-------------------------

- [x] Issue 5:

Cannot withdraw an assym BCH.BCH position. It says "PROCESSING" then reverts to "CONFIRM" in red in the breadcrumb after. You can't remove your position. It only happens to BCH.BCH.

**Comment by SKIPexchange** [comment]
It seems there is a problem within the BCH pool in testnet it shows a negative amount for me.
