### ISSUE TITLE
Missing nav icons after keystore creation

### ISSUE THREAD

**Issue by anonfiveone** [SKIPexchange/asgard-exchange#215]
- [x] ![IMG_D6257F82A37B-1](https://user-images.githubusercontent.com/83097467/129651584-2400120d-3fa0-4739-b92e-7f070c039d6b.jpeg)

**Comment by SKIPexchange** [comment]
Worked for me it might be an internet issue or something WEIRD.

![image](https://user-images.githubusercontent.com/82870243/130046737-cecdbc0a-ba25-4e2c-aff5-b64782b20579.png)
